### ISSUE TITLE
clearUnwalkableTriangles should be public.

### ISSUE THREAD

**Issue by mitm001** [ppiastucki/recast4j#51]
Hi Piotr,

Got something for you to check out before you release 1.2.4.

https://groups.google.com/forum/#!searchin/recastnavigation/flag$20triangles$20in$20navmesh%7Csort:date/recastnavigation/vuyOHdG8NkQ/AA8dOHKYBwAJ

The method markWalkableTriangles is public but clearUnwalkableTriangles is not. Can you make this public?

https://github.com/ppiastucki/recast4j/blob/66a523fc5d14efe05dcb38a197e2c5b670f652ca/recast/src/main/java/org/recast4j/recast/Recast.java#L93

This test is not implemented, 

https://github.com/recastnavigation/recastnavigation/blob/05b2b8da80037887d3e79af8a59a8f0f8ed02602/Tests/Recast/Tests_Recast.cpp#L484

Do you have any examples that make use of adding multiple navmeshes and setting the area types using clearUnwalkableTriangles?

https://github.com/ppiastucki/recast4j/blob/9fa8ae5562e9b6cf74b8717abc3cc296f68494c0/recast/src/test/java/org/recast4j/recast/RecastSoloMeshTest.java#L125

Any input would be appreciated.

**Comment by ppiastucki** [comment]
Thanks for reporting that.
I will make clearUnwalkableTriangles public of course, but you can see that recast4j contains some functionality from release-2.0 branch of recast (https://github.com/recastnavigation/recastnavigation/blob/release-2.0/Recast/Source/Recast.cpp#L307) and you can pass you area type modification to markWalkableTriangles in order to set whatever area type you want instead of the default of RC_WALKABLE_AREA.
I guess it makes clearUnwalkableTriangles a bit useless, but since it is still in release-2.0 branch I will keep it in recast4j too.
I am not sure when it is planned to merge this feature from 2.0 to master or release 2.0, you can probably ask recast developers.
